html-relative-links - Raene Horist
Raenbow/lfz-alumni-code-solutions pull request #6
Opened 2022-04-19 21:50 UTC by Raenbow

2022-04-19 23:40 UTC, TimelikeClosure requested changes
@Raenbow Can you please include a video of you navigating through the pages?

2022-04-20 03:54 UTC, Raenbow commented
https://user-images.githubusercontent.com/34592143/164147105-9dc38a29-e332-4ddc-90cb-7cb2d8060d64.mp4

2022-04-22 02:41 UTC, Raenbow commented
@TimelikeClosure Figured out the video issue!

2022-04-22 02:46 UTC, TimelikeClosure approved these changes

2022-04-22 02:49 UTC, merged