html-forms - Raene Horist
Raenbow/lfz-alumni-code-solutions pull request #7
Opened 2022-04-20 20:27 UTC by Raenbow

https://user-images.githubusercontent.com/34592143/164317041-710a6725-ca00-4f0f-8a8d-142975f21744.mp4

2022-04-20 21:42 UTC, TimelikeClosure requested changes

2022-04-20 21:42 UTC, TimelikeClosure commented on html-forms/index.html
> +        <button>Submit</button>
It's generally a good idea to specify the `type` attributes on `<button>`s, even if they have the default `type`.

2022-04-20 21:42 UTC, TimelikeClosure commented on html-forms/index.html
> +          <input type="text" name="email" />
For `<input>`s that should hold email addresses, try `type="email"`.

2022-04-21 17:38 UTC, Raenbow commented
@TimelikeClosure I made the changes you suggested as well as adding labels to the radio inputs and adjusting the 'for' attributes on the labels.

2022-04-21 23:43 UTC, TimelikeClosure requested changes

2022-04-21 23:43 UTC, TimelikeClosure commented on html-forms/index.html
> +        <label for="reasons">Why is coding cool?</label>
As counter-intuitive as it is, a `<label>`'s `for` attribute refers to a form control by `id`, not by `name`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

2022-04-22 02:40 UTC, TimelikeClosure approved these changes

2022-04-22 02:42 UTC, merged